import { ProbeResult } from "./catalog";

/**
 * A real run, recorded from the live Docker stack on 2026-09-17.
 * Served when the backend isn't reachable (e.g. the public deployment,
 * where the API only runs locally). Always labelled as recorded in the UI.
 */
export const SNAPSHOT_DATE = "2026-09-17";

export const SNAPSHOT: ProbeResult[] = [
  {
    "id": "bola-read-profile",
    "category": "API1",
    "title": "Read another account's profile",
    "method": "GET",
    "path": "/auth/users/:userId",
    "severity": "HIGH",
    "expected": "403",
    "pass": true,
    "got": "403",
    "request": "GET /auth/users/<id>\nAuthorization: Bearer <account B>   # profile owned by account A",
    "response": "403\n{\n  \"success\": false,\n  \"message\": \"Access denied\"\n}",
    "note": "Ownership compared against the id in the token, not the URL."
  },
  {
    "id": "bola-edit-profile",
    "category": "API1",
    "title": "Edit another account's profile",
    "method": "PUT",
    "path": "/auth/users/:userId",
    "severity": "HIGH",
    "expected": "403",
    "pass": true,
    "got": "403",
    "request": "PUT /auth/users/<id>\nAuthorization: Bearer <account B>\n\n{\"data\":{\"username\":\"hijacked\",\"email\":\"hijacked@probe.local\",\"password\":\"Probe_pw_123\"}}",
    "response": "403\n{\n  \"success\": false,\n  \"message\": \"Access denied\"\n}",
    "note": "Rejected before any write."
  },
  {
    "id": "bola-list-orders",
    "category": "API1",
    "title": "List another account's orders",
    "method": "GET",
    "path": "/orders/user/:userId",
    "severity": "HIGH",
    "expected": "403",
    "pass": true,
    "got": "403",
    "request": "GET /orders/user/<id>\nAuthorization: Bearer <account B>",
    "response": "403\n{\n  \"success\": false,\n  \"message\": \"Access denied\"\n}",
    "note": "Order listing checks the caller's id."
  },
  {
    "id": "auth-no-token",
    "category": "API2",
    "title": "Call a protected route with no token",
    "method": "GET",
    "path": "/auth/users/:userId",
    "severity": "HIGH",
    "expected": "401",
    "pass": true,
    "got": "401",
    "request": "GET /auth/users/<id>\n(no Authorization header)",
    "response": "401\n{\n  \"success\": false,\n  \"message\": \"Missing bearer token\"\n}",
    "note": "Global guard rejects tokenless requests."
  },
  {
    "id": "auth-alg-none",
    "category": "API2",
    "title": "Unsigned token (alg: none)",
    "method": "GET",
    "path": "/auth/users/:userId",
    "severity": "HIGH",
    "expected": "401",
    "pass": true,
    "got": "401",
    "request": "GET /auth/users/<id>\nAuthorization: Bearer eyJhbGciOiJub25lIn0...   # unsigned",
    "response": "401\n{\n  \"success\": false,\n  \"message\": \"Invalid or expired token\"\n}",
    "note": "Unsigned tokens are rejected."
  },
  {
    "id": "auth-default-secret",
    "category": "API2",
    "title": "Token signed with the documented default secret",
    "method": "GET",
    "path": "/auth/users/:userId",
    "severity": "HIGH",
    "expected": "401",
    "pass": true,
    "got": "401",
    "request": "GET /auth/users/<id>\nAuthorization: Bearer <HS256, secret = change_me_in_production>",
    "response": "401\n{\n  \"success\": false,\n  \"message\": \"Invalid or expired token\"\n}",
    "note": "Server secret differs from the documented default."
  },
  {
    "id": "auth-tampered-sub",
    "category": "API2",
    "title": "Real token with its user id swapped",
    "method": "GET",
    "path": "/auth/users/:userId",
    "severity": "HIGH",
    "expected": "401",
    "pass": true,
    "got": "401",
    "request": "GET /auth/users/<id>\nAuthorization: Bearer <account B token, sub rewritten to A>",
    "response": "401\n{\n  \"success\": false,\n  \"message\": \"Invalid or expired token\"\n}",
    "note": "Editing the payload invalidates the signature."
  },
  {
    "id": "prop-mass-assign",
    "category": "API3",
    "title": "Smuggle a role field into a profile update",
    "method": "PUT",
    "path": "/auth/users/:userId",
    "severity": "HIGH",
    "expected": "400",
    "pass": true,
    "got": "400",
    "request": "PUT /auth/users/<id>\nAuthorization: Bearer <account A>\n\n{\"data\":{\"username\":\"ok\",\"email\":\"ok@probe.local\",\"password\":\"Probe_pw_123\",\"role\":\"admin\",\"isVerified\":true}}",
    "response": "400\n{\n  \"message\": [\n    \"property role should not exist\",\n    \"property isVerified should not exist\"\n  ],\n  \"error\": \"Bad Request\",\n  \"statusCode\": 400\n}",
    "note": "Undeclared fields (role, isVerified) rejected by the validation pipe."
  },
  {
    "id": "prop-password-leak",
    "category": "API3",
    "title": "Password hash in profile response",
    "method": "GET",
    "path": "/auth/users/:userId",
    "severity": "HIGH",
    "expected": "no password field",
    "pass": true,
    "got": "clean",
    "request": "GET /auth/users/<id>\nAuthorization: Bearer <account A>",
    "response": "200\n{\n  \"success\": true,\n  \"message\": \"User found successfully\",\n  \"data\": {\n    \"id\": \"<id>\",\n    \"username\": \"probe_user\",\n    \"email\": \"probe_user@probe.local\",\n    \"createdAt\": \"2026-09-17T12:07:42.120Z\",\n    \"updatedAt\": \"2026-09-17T12:07:42.120Z\"\n  }\n}",
    "note": "No password field returned."
  },
  {
    "id": "rate-login-burst",
    "category": "API4",
    "title": "Password guessing burst",
    "method": "POST",
    "path": "/auth/login ×7",
    "severity": "MED",
    "expected": "429",
    "pass": true,
    "got": "429",
    "request": "POST /auth/login ×7\nx-user-id: burst-fixed\nwrong credentials",
    "response": "codes: 401 401 401 401 401 429 429",
    "note": "Login bucket blocks after 5 attempts."
  },
  {
    "id": "rate-rotated-key",
    "category": "API4",
    "title": "Burst with a new x-user-id on every request",
    "method": "POST",
    "path": "/auth/login ×7",
    "severity": "MED",
    "expected": "429",
    "pass": false,
    "got": "401",
    "request": "POST /auth/login ×7\nx-user-id: rot-0, rot-1, …   # new value each time",
    "response": "codes: 401 401 401 401 401 401 401",
    "note": "Rotating the self-reported x-user-id dodged the per-user limit; only the IP bucket remains."
  },
  {
    "id": "rbac-delete-product",
    "category": "API5",
    "title": "Delete a product from an ordinary account",
    "method": "DELETE",
    "path": "/products/:id",
    "severity": "HIGH",
    "expected": "403",
    "pass": false,
    "got": "200",
    "request": "DELETE /products/<id>\nAuthorization: Bearer <ordinary account>",
    "response": "200\n{\n  \"success\": true,\n  \"message\": \"Product deleted successfully\"\n}",
    "note": "No role check — any signed-in account can delete products."
  },
  {
    "id": "rbac-delete-category",
    "category": "API5",
    "title": "Delete a category from an ordinary account",
    "method": "DELETE",
    "path": "/categories/:id",
    "severity": "HIGH",
    "expected": "403",
    "pass": false,
    "got": "200",
    "request": "DELETE /categories/<id>\nAuthorization: Bearer <ordinary account>",
    "response": "200\n{\n  \"success\": true,\n  \"message\": \"Category deleted successfully\",\n  \"data\": {\n    \"id\": \"<id>\",\n    \"name\": \"probe-cat-1789646862863\",\n    \"description\": \"probe\",\n    \"createdAt\": \"2026-09-17T12:07:42.867Z\",\n    \"updatedAt\": \"2026-09-17T12:07:42.867Z\"\n  }\n}",
    "note": "No role check — any signed-in account can delete categories."
  },
  {
    "id": "flow-burst-register",
    "category": "API6",
    "title": "Register 5 accounts back-to-back, no verification gate",
    "method": "POST",
    "path": "/auth/register ×5",
    "severity": "MED",
    "expected": "throttled or blocked",
    "pass": false,
    "got": "5/5 succeeded",
    "request": "POST /auth/register ×5\n5 unique accounts, back-to-back, no delay between them",
    "response": "codes: 201 201 201 201 201",
    "note": "All 5 accounts were created instantly — no CAPTCHA, email verification, or signup-specific throttle stood in the way."
  },
  {
    "id": "ssrf-shipping-destination",
    "category": "API7",
    "title": "Shipping estimate with a cloud-metadata URL as destination",
    "method": "POST",
    "path": "/shipping/estimate",
    "severity": "MED",
    "expected": "rejected before reaching business logic",
    "pass": true,
    "got": "400",
    "request": "POST /shipping/estimate\n\n{\"destination\":\"http://169.254.169.254/latest/meta-data/iam/security-credentials/\",\"weight\":5,\"dimensions\":{\"length\":1,\"width\":1,\"height\":1}}",
    "response": "400\n{\n  \"message\": [\n    \"property destination should not exist\",\n    \"property weight should not exist\",\n    \"property dimensions should not exist\"\n  ],\n  \"error\": \"Bad Request\",\n  \"statusCode\": 400\n}",
    "note": "The destination field never reaches any logic — every field is rejected before the handler runs. (The DTO has no validators, so this blocks legitimate estimate requests too, not just this payload.)"
  },
  {
    "id": "ssrf-image-url",
    "category": "API7",
    "title": "Product image URL pointing at an internal/metadata address",
    "method": "POST",
    "path": "/products",
    "severity": "LOW",
    "expected": "stored verbatim, never fetched",
    "pass": true,
    "got": "stored, not fetched",
    "request": "POST /products\nAuthorization: Bearer <account A>\n\n{\"name\":\"probe-ssrf-image\",\"description\":\"x\",\"price\":1,\"imageUrl\":\"http://169.254.169.254/latest/meta-data/iam/security-credentials/\"}",
    "response": "201\n{\n  \"success\": true,\n  \"message\": \"Product created successfully\",\n  \"data\": {\n    \"id\": \"<id>\",\n    \"createdAt\": \"2026-09-17T12:07:43.946Z\",\n    \"updatedAt\": \"2026-09-17T12:07:43.946Z\",\n    \"name\": \"probe-ssrf-image\",\n    \"description\": \"x\",\n    \"price\": 1,\n    \"imageUrl\": \"http://169.254.169.254/latest/meta-data/iam/security-credentials/\"\n  }\n}",
    "note": "The URL is stored as plain text and returned unmodified — nothing on the server ever dereferences it."
  },
  {
    "id": "misconf-headers",
    "category": "API8",
    "title": "Security response headers",
    "method": "GET",
    "path": "/health",
    "severity": "LOW",
    "expected": "nosniff, no x-powered-by",
    "pass": true,
    "got": "ok",
    "request": "GET /health",
    "response": "x-content-type-options: nosniff\nx-frame-options: SAMEORIGIN\nx-powered-by: (removed)",
    "note": "Helmet defaults applied."
  },
  {
    "id": "misconf-cors",
    "category": "API8",
    "title": "CORS for an untrusted origin",
    "method": "GET",
    "path": "/health",
    "severity": "MED",
    "expected": "origin not allowed",
    "pass": true,
    "got": "blocked",
    "request": "GET /health\nOrigin: https://evil.example",
    "response": "access-control-allow-origin: (not set)",
    "note": "Untrusted origin not reflected."
  },
  {
    "id": "misconf-swagger",
    "category": "API8",
    "title": "API schema reachable without a token",
    "method": "GET",
    "path": "/api-json",
    "severity": "LOW",
    "expected": "404",
    "pass": true,
    "got": "404",
    "request": "GET /api-json",
    "response": "404",
    "note": "Swagger not mounted (production build)."
  },
  {
    "id": "misconf-malformed-json",
    "category": "API8",
    "title": "Malformed JSON body doesn't leak a stack trace",
    "method": "POST",
    "path": "/auth/login",
    "severity": "LOW",
    "expected": "generic 400, no stack or file paths",
    "pass": true,
    "got": "clean 400",
    "request": "POST /auth/login\ncontent-type: application/json\nbody: {bad json   # malformed",
    "response": "400\n{\n  \"message\": \"Expected property name or '}' in JSON at position 1\",\n  \"error\": \"Bad Request\",\n  \"statusCode\": 400\n}",
    "note": "Parse error is generic — no stack trace or file path in the response."
  },
  {
    "id": "misconf-unknown-route",
    "category": "API8",
    "title": "Unknown route returns a clean 404",
    "method": "GET",
    "path": "/this-route-does-not-exist",
    "severity": "LOW",
    "expected": "json 404, not an html error page",
    "pass": true,
    "got": "clean 404",
    "request": "GET /this-route-does-not-exist",
    "response": "404\n{\n  \"message\": \"Cannot GET /this-route-does-not-exist\",\n  \"error\": \"Not Found\",\n  \"statusCode\": 404\n}",
    "note": "Unknown routes return a plain JSON 404 — no framework HTML error page."
  },
  {
    "id": "inventory-sessions-list",
    "category": "API9",
    "title": "Session list without a token",
    "method": "GET",
    "path": "/gateway/_sessions",
    "severity": "HIGH",
    "expected": "401",
    "pass": true,
    "got": "401",
    "request": "GET /gateway/_sessions\n(no Authorization header)",
    "response": "401\n{\n  \"success\": false,\n  \"message\": \"Missing bearer token\"\n}",
    "note": "Admin/debug endpoint requires a token like everything else."
  },
  {
    "id": "inventory-session-lookup",
    "category": "API9",
    "title": "Inspect a specific session by guessed ID, no token",
    "method": "GET",
    "path": "/gateway/_sessions/:sessionId",
    "severity": "HIGH",
    "expected": "401",
    "pass": true,
    "got": "401",
    "request": "GET /gateway/_sessions/guessed-session-id\n(no Authorization header)",
    "response": "401\n{\n  \"success\": false,\n  \"message\": \"Missing bearer token\"\n}",
    "note": "Guessing a session id doesn't help — it still requires auth."
  },
  {
    "id": "inventory-legacy-path",
    "category": "API9",
    "title": "Request a legacy/shadow API version path",
    "method": "GET",
    "path": "/api/v1/products",
    "severity": "LOW",
    "expected": "404",
    "pass": true,
    "got": "404",
    "request": "GET /api/v1/products",
    "response": "404",
    "note": "No orphaned legacy-version route lingering behind the current API."
  }
];
