name: Test Inactive Issue Script

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allow manual triggering

permissions: read-all

jobs:
  run-inactive-issue-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests library
        run: pip install requests

      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TEST_GITHUB_APP_ID }}
          private-key: ${{ secrets.TEST_GITHUB_APP_PRIVATE_KEY }}

      - name: Run inactive issue checker script
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          DEASSIGN_INACTIVE_CONTRIBUTORS: 'false'  # Set to false for testing
        run: |
          echo "Running inactive issue checker script with enhanced logging..."
          python -m backend.api-inventory.src.inactive_issue_checker